openapi: 3.0.3
info:
  title: Automation API
  version: 1.0.0
  description: An automated platform tasks, mails, approvals..
paths:
  /customers/refresh/:
    post:
      operationId: customers_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /customers/token/:
    post:
      operationId: customers_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - customers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /executions/execute-workflow/:
    post:
      operationId: executions_execute_workflow_create
      tags:
      - executions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowExecution'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/WorkflowExecution'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/WorkflowExecution'
        required: true
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowExecution'
          description: ''
  /workflows/workflow-step-create/:
    post:
      operationId: workflows_workflow_step_create_create
      tags:
      - workflows
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /workflows/workflow/{workflow_id}/workflow-delete:
    delete:
      operationId: workflows_workflow_workflow_delete_destroy
      parameters:
      - in: path
        name: workflow_id
        schema:
          type: integer
        required: true
      tags:
      - workflows
      security:
      - jwtAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /workflows/workflow/{workflow_id}/workflow-detail:
    get:
      operationId: workflows_workflow_workflow_detail_retrieve
      parameters:
      - in: path
        name: workflow_id
        schema:
          type: integer
        required: true
      tags:
      - workflows
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /workflows/workflows-lists/:
    get:
      operationId: workflows_workflows_lists_retrieve
      tags:
      - workflows
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    StatusEnum:
      enum:
      - pending
      - running
      - paused
      - completed
      - failed
      type: string
      description: |-
        * `pending` - Pending
        * `running` - Running
        * `paused` - Paused
        * `completed` - Completed
        * `failed` - Failed
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    WorkflowExecution:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        status:
          $ref: '#/components/schemas/StatusEnum'
        context: {}
        started_at:
          type: string
          format: date-time
          readOnly: true
        finished_at:
          type: string
          format: date-time
          nullable: true
        workflow:
          type: integer
        triggered_by:
          type: integer
          nullable: true
      required:
      - context
      - id
      - started_at
      - status
      - workflow
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
