# Generated by Django 6.0 on 2025-12-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exections', '0002_stepexecution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowexecution',
            options={'ordering': ['-started_at']},
        ),
    ]
